### ISSUE TITLE
Build and Ship: A Messaging App with Python!

### ISSUE THREAD

**Issue by dstarner15** [ubacm/ubacm#14]

**Comment by StephenOrJames** [comment]
Just a note that we're planning to do a Python workshop (in collaboration with UB Robotics), most likely building from what you did last year (see #6). It's still in the early stages of planning, but let us know if you're interested in helping out with that.

**Comment by angushtlam** [comment]
Three part event scheduled:
10/2/2017 5-6:30pm
10/5/2017 5-6:30pm
10/9/2017 5-6:30pm
