### ISSUE TITLE
Internship Panel

### ISSUE THREAD

**Issue by angushtlam** [ubacm/ubacm#16]

**Comment by angushtlam** [comment]
Scientista is interested in running this event together

**Comment by angushtlam** [comment]
Document about the event can be found here.

https://docs.google.com/document/d/1d1DBmHbwCGkrTVyx0L5vuLuaONdtvjO-TRs6a0_Ofvs/edit

**Comment by angushtlam** [comment]
Date confirmed for Mon, September 18, 5pm – 6pm

**Comment by RychardHunt** [comment]
Completed.
