### ISSUE TITLE
Parallel Computing Tech Talk

### ISSUE THREAD

**Issue by angushtlam** [ubacm/ubacm#21]
Peter Gottesman has a contact from Cisco who is interested in giving a tech talk on Parallel Computing (remotely). Working on getting details for an event.

https://github.com/open-mpi/ompi

**Comment by angushtlam** [comment]
jsquyres@cisco.com

**Comment by angushtlam** [comment]
Event scheduled for Nov 30th. Jeff will videoconference with us.

**Comment by TristanWiley** [comment]
oooh :+1:
