### ISSUE TITLE
Get a bus to Kent Hack Enough

### ISSUE THREAD

**Issue by TristanWiley** [ubacm/ubacm#27]
In contact with Kent Hack Enough to try to get a bus to get our hackers there.

khe.io

**Comment by angushtlam** [comment]
i belieeeeeeeve

**Comment by angushtlam** [comment]
rip dream. It's too expensive. We can organize carpool for this

**Comment by TristanWiley** [comment]
KHE is working with us to get as many carpoolers with reimbursements as possible. #UBTakingOverTheRoadsOn Sep 12, 2017 1:30 PM, Angus Lam <notifications@github.com> wrote:rip dream. It's too expensive. We can organize carpool for this
