### ISSUE TITLE
Interview Prep (Peer to Peer)

### ISSUE THREAD

**Issue by RychardHunt** [ubacm/ubacm#31]
Will announce on Monday General Meeting.

**Comment by angushtlam** [comment]
Can I have more information on the event details?

**Comment by RychardHunt** [comment]
Create 2 slack channels. One for upperclassmen and one for underclassmen. Just have them join and figure out where and when to meet to practice and analyze leetcode questions. Thus the peer to peer nature.

**Comment by angushtlam** [comment]
Oh, I see, this is a good idea!

If you got some time, maybe we can write some copy about this to tell people what the event is about

**Comment by RychardHunt** [comment]
I don't think this is an event in which ACM will be actively participating in. My vision for this is to just give people a platform to interview prep with peers and give constructive critisicm to each other. We will have an internship panel and resume review workshop sometime soon in which we will have to actively participate and plan things.

**Comment by angushtlam** [comment]
Program announced.
