### ISSUE TITLE
Blaze Gawlik - CTO FrescoNews Tech Talk (Spring Semester)

### ISSUE THREAD

**Issue by wafflez180** [ubacm/ubacm#39]
Blaze, a friend of mine from FrescoNews would like to do a talk (unsure what topic to talk about) in the spring semester. This talk has yet to be planned.

https://www.linkedin.com/in/blaze-gawlik-3b06b294/

**Comment by angushtlam** [comment]
yaaaaas 🎉

**Comment by PeterGottesman** [comment]
@wafflez180 do you want to follow up on this with him?

**Comment by wafflez180** [comment]
@PeterGottesman Yeah, I'll be following up with him sometime in the next 2 weeks. Thanks for the reminder

**Comment by StephenOrJames** [comment]
Done!
