### ISSUE TITLE
Engineering Club Fair / Need members to cover shifts

### ISSUE THREAD

**Issue by angushtlam** [ubacm/ubacm#4]
I've registered UB ACM for the Engineering Club Fair on Mon, August 28 in Davis from 12pm - 2:30pm.

Completing this event from start to finish will provide UB ACM with 1 Community Service credit.

As of now, we have
12pm-1pm shift
 - Angus

1pm-2pm shift
 - Richard H.

2pm-2:30pm shift
 - Richard G.

**Comment by StephenOrJames** [comment]
Note that the event ends at 2:30pm. I could potentially head back after the 2pm shift if anything.

**Comment by angushtlam** [comment]
@StephenOrJames I won't be able to come back, we're at least going to need someone to cover 1pm-2pm in order to get the credit. :/

**Comment by angushtlam** [comment]
We now have someone filling every time slot! 🎉

Would be great if we can get more people staffing, but should be fine on the credit side.

**Comment by StephenOrJames** [comment]
Have we been registered for the event, or does that still need to be done?

**Comment by angushtlam** [comment]
We are registered.
