### ISSUE TITLE
workshop.py

### ISSUE THREAD

**Issue by angushtlam** [ubacm/ubacm#6]
UB Robotics is interested in running an introductory Python workshop with UB ACM. There hasn't been any planning done yet, but since UB ACM ran an Intro to Python workshop previously, we have some available content https://github.com/ubacm/python-tutorial to use.

Feel free to change the workshop however you want.

ACM Members:
- Stephen James
- Richard Hanulewicz
- Rychard Guo

**Comment by angushtlam** [comment]
Is this confirmed to be on Monday 9/11?

**Comment by StephenOrJames** [comment]
No, a date hasn't been decided as yet, and I personally have too much going on this week to guarantee that date from now.

**Comment by angushtlam** [comment]
I slotted a temporary time for 9/25/2017 5-6 for the event, but feel free to move it to whenever you'd like

**Comment by RychardHunt** [comment]
If this event will ever happen, it should happen before our data science python workshop. Alternatively, we can make this part of our data science python workshop where we'll mostly be teaching the parts relevant to the data science workshop.

**Comment by angushtlam** [comment]
Dan is going to be planning/running his multi-day Docker workshop, so he won't be able to help out with this one.

**Comment by StephenOrJames** [comment]
Considering that covering the content would take some time, could we either extend the time on the Monday or continue into the Thursday (September 28) which currently seems available?

**Comment by angushtlam** [comment]
its up to you, you can do either option

**Comment by RychardHunt** [comment]
I think we should just make it 2 days, because it would be difficult to keep people's attention for longer than an hour. Thursday is available anyways, so we should have an event on that day.

**Comment by StephenOrJames** [comment]
Let's do that then.

**Comment by angushtlam** [comment]
@rshanule

**Comment by rshanule** [comment]
Added to calendar

**Comment by RychardHunt** [comment]
Completed
