### ISSUE TITLE
SA Participation Credit / How to Social Media and Marketing Your Club

### ISSUE THREAD

**Issue by angushtlam** [ubacm/ubacm#9]
Need 3 members to attend one of the following sessions.

Tuesday 9/12/2017 6pm-7pm SU 330
Wednesday 9/13/2017 6pm-7pm SU 330

[SA Participation Doc](https://docs.google.com/spreadsheets/d/1dqlPKtk_RqnDP6YfPfA7cRU9lLBPZ2QO8OuE_Kvxm88/edit#gid=0)

**Comment by rshanule** [comment]
Either of those datetimes are good for me

**Comment by angushtlam** [comment]
Whoops forgot about this :/

**Comment by rshanule** [comment]
crap
